<div class="container my-5">
    <div class="card border-secondary mb-3">
        <div class="card-header">
            <h3><?= $params["championship"]["nev"] ?></h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-4">
                    <h4 class="">Kezdete:</h4>
                </div>
                <div class="col-lg-8">
                    <h4 class=""><?= $params["championship"]["kezdes"] ?></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <h4 class="">Vége:</h4>
                </div>
                <div class="col-lg-8">
                    <h4 class=""><?= $params["championship"]["vege"] ?></h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <h4 class="">Meccsek:</h4>
                </div>
                <div class="col-lg-8">
                    <h4 class="d-inline-block"> <?= count($params["championship"]["lejatszott-meccsek"]) ?> / <?= $params["championship"]["meccsekSzama"] ?></h4>
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: <?= count($params["championship"]["lejatszott-meccsek"])  / $params["championship"]["meccsekSzama"] * 100 ?>%;" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if ($_SESSION["role"] == 1) : ?>
    <div class="container text-center mb-5">
        <a href="/uj-meccsek/<?= $params["championship"]["id"] ?>" class="btn btn-lg btn-outline-success" type="button"><span class="p-2"><i class="fas fa-plus"></i></span> Új meccsek</a>
    </div>
<?php endif; ?>
<h1 class="text-center my-4">Meccsek</h1>


<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active mb-3" data-bs-toggle="tab" href="#aktiv-meccsek">Aktív meccsek</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" href="#lejatszott-meccsek">Lejátszott meccsek</a>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active show" id="aktiv-meccsek">
            <div class="table-responsive">
                <table class="table table-bordered " style="overflow: hidden; white-space:nowrap">
                    <thead class="text-center">
                        <tr class="table-dark">
                            <th>#</th>
                            <th>Kezdés</th>
                            <th>Hazai</th>
                            <th>Vendég</th>
                            <th>Csoport</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($params["championship"]["aktiv-meccsek"] as $activeMatch) : ?>
                            <tr class="">
                                <td><?= $activeMatch["Id"] ?></td>
                                <td><?= date('Y-m-d H:i', strtotime($activeMatch["Kezdes"]));  ?></td>
                                <td><?= $activeMatch["Hazai"] ?></td>
                                <td><?= $activeMatch["Vendeg"] ?></td>
                                <td><?= $activeMatch["csoport"] ?></td>
                                <td>
                                    <?php if ($_SESSION["role"] == 1) : ?>
                                        <a href="/meccs-szerkesztes/<?= $activeMatch["Id"] ?>"" style=" margin-right: 5px;" class="btn btn-outline-warning"><i class="fas fa-pencil-alt"></i></a>
                                        <form class="d-inline" action="/meccs-torles/<?= $activeMatch["Id"] ?>" method="POST"><button class="btn btn-outline-danger" href=""><i class="fas fa-times"></i></a></form>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-pane fade show" id="lejatszott-meccsek">
            <div class="table-responsive">
                <table class="table table-bordered " style="overflow: hidden; white-space:nowrap">
                    <thead class="text-center">
                        <tr class="table-dark">
                            <th>#</th>
                            <th>Időpont</th>
                            <th>Hazai</th>
                            <th>Vendég</th>
                            <th>Csoport</th>
                            <th>Eredmény</th>
                            <!-- <th></th> -->
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($params["championship"]["lejatszott-meccsek"] as $closedMatch) : ?>
                            <tr class="">
                                <td><?= $closedMatch["id"] ?></td>
                                <td><?= date('Y-m-d H:i', strtotime($closedMatch["Kezdes"]));  ?></td>
                                <td><?= $closedMatch["Hazai"] ?></td>
                                <td><?= $closedMatch["Vendeg"] ?></td>
                                <td><?= $closedMatch["csoport"] ?></td>
                                <td><?= $closedMatch["hazaiEredmeny"] . " - " . $closedMatch["vendegEredmeny"]  ?></td>
                                <!-- <td>
                                    <a style="margin-right: 5px;" class="btn btn-outline-warning" href=""><i class="fas fa-pencil-alt"></i></a>
                                    <a class="btn btn-outline-danger" href=""><i class="fas fa-times"></i></a>
                                </td> -->
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<h1 class="text-center my-4">Tippek</h1>
<div class="container">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active mb-3" data-bs-toggle="tab" href="#aktiv-tippek">Aktív Tippek</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" href="#sajat-tippek">Saját Tippek</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="tab" href="#masok-tippjei">Mások Tippjei</a>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active show" id="aktiv-tippek">
            <?php if (count($params["activeTips"]) > 0) : ?>
                <div class="container mt-5">
                    <form method="POST" action="/tippek-leadasa">
                        <input type="hidden" name="bajnoksag-id" value="<?= $params["championship"]["id"] ?>">
                        <div id="meccsek" class="container">
                            <?php foreach ($params["activeTips"] as $tip) : ?>
                                <input type="hidden" name="meccs-id[]" value="<?= $tip["meccsId"] ?>">
                                <div class="form-group row mb-4">
                                    <div class="col-lg-2 ">
                                        <label class="form-label lead" for="kezdes"><?= date('Y-m-d H:i', strtotime($tip["kezdes"])); ?></label>
                                        <input type="hidden" name="kezdes[]" value="<?= $tip["kezdes"] ?>">
                                    </div>
                                    <div class="col-lg-2 ">
                                        <label for="hazai-eredmeny" class="form-label lead"><?= $tip["hazai"] ?></label>
                                    </div>
                                    <div class="col-lg-2 ">
                                        <input name="hazai-eredmeny[]" type="number" min="0" class="form-control" required>
                                    </div>
                                    <div class="col-lg-2 ">
                                        <label for="vendeg-eredmeny" class="form-label lead"><?= $tip["vendeg"] ?></label>
                                    </div>
                                    <div class="col-lg-2 ">
                                        <input name="vendeg-eredmeny[]" type="number" min="0" class="form-control" required>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="container text-center">
                            <div class="">
                                <button style="margin-right: 10px;" class="btn btn-block btn-outline-danger" type="submit"><span class="p-2"><i class="fas fa-save"></i></span> Mentés</button>
                            </div>
                        </div>
                    </form>
                </div>
            <?php endif; ?>
        </div>
        <div class="tab-pane fade show" id="sajat-tippek">

            <div class="table-responsive">
                <table class="table table-bordered " style="overflow: hidden; white-space:nowrap">
                    <thead class="text-center">
                        <tr class="table-dark">
                            <th>#</th>
                            <th>Meccs</th>
                            <th>Tipp</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($params["ownGivenTips"] as $givenTip) : ?>
                            <tr class="">
                                <td><?= $givenTip["Id"] ?></td>
                                <td><?= $givenTip["meccs"] ?></td>
                                <td><?= $givenTip["tipp"] ?></td>
                                <td>
                                    <?php if ($givenTip["lejatszott"] == 0) : ?>
                                        <form class="d-inline" action="/tipp-torles/<?= $givenTip["tippId"] ?>" method="POST"><button class="btn btn-outline-danger" href=""><i class="fas fa-times"></i></a></form>
                                    <?php endif; ?>
                                </td>
                            </tr>

                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <script>
            var tippek = <?php echo json_encode($params["ownGivenTips"] ) ?>;
        </script>
        <div class="tab-pane fade show" id="masok-tippjei">
            <div class="table-responsive">
                <table class="table table-bordered " style="overflow: hidden; white-space:nowrap">
                    <thead class="text-center">
                        <tr class="table-dark">
                            <th>#</th>
                            <th>Meccs</th>
                            <th>Tippek</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($params["othersGivenTips"] as $givenTip) : ?>
                            <tr class="">
                                <td><?= $givenTip["Id"] ?></td>
                                <td><?= $givenTip["meccs"] ?></td>
                                <td><?= $givenTip["tippek"] ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<h1 class="text-center my-4">Tabella</h1>
<div class="container ">
    <div class="table-responsive">
        <table class="table table-bordered " style="overflow: hidden; white-space:nowrap">
            <thead class="text-center">
                <tr class="table-dark">
                    <th>#</th>
                    <th>Név</th>
                    <th>Pontok</th>
                    <th>Telitalálatok</th>
                    <th>Forma</th>
                </tr>
            </thead>
            <tbody class="text-center" style="overflow: hidden; white-space:nowrap">
                <?php foreach ($params["players"] as $player) : ?>
                    <tr class="">
                        <td><?= $player["id"] ?></td>
                        <td><?= $player["nev"] ?></td>
                        <td><?= $player["pontok"]["osszpont"]; ?></td>
                        <td><?= $player["pontok"]["telitalalat"]; ?></td>
                        <td s style="overflow: hidden; white-space:nowrap">
                            <?php foreach ($player["tippek"] as $tipp) : ?>
                                <?php switch ($tipp["pont"]):
                                    case 3: ?>
                                        <button style="margin-right: 5px;" type="button" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="<?= $tipp["hcs"] . " " . $tipp["hazaiEredmeny"] . " - " . $tipp["vendegEredmeny"] . " " . $tipp["vcs"]   ?>"><i class="far fa-check-circle fa-lg"></i></button>
                                        <?php break; ?>
                                    <?php
                                    case 1: ?>
                                        <button style="margin-right: 5px;" type="button" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="<?= $tipp["hcs"] . " " . $tipp["hazaiEredmeny"] . " - " . $tipp["vendegEredmeny"] . " " . $tipp["vcs"]   ?>"><i class="far fa-dot-circle fa-lg"></i></button>
                                        <?php break; ?>
                                    <?php
                                    case 0: ?>
                                        <button style="margin-right: 5px;" type="button" class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="<?= $tipp["hcs"] . " " . $tipp["hazaiEredmeny"] . " - " . $tipp["vendegEredmeny"] . " " . $tipp["vcs"]   ?>"><i class="far fa-times-circle fa-lg"></i></button>
                                        <?php break; ?>
                                <?php endswitch; ?>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>