<h1 class="text-center my-4 text-white">Bejelentkezés</h1>

<div class="container">
    <form method="POST" action="/login">
        <div id="meccsek" class="container text-white">
            <div class="form-group row mb-4">
                <label for="nev" class="col-sm-2 form-label lead fw-bold">Név</label>
                <div class="col-sm-10">
                    <input type="text"  class="form-control bg-secondary text-white" name="nev"  required>
                </div>
            </div>
            <div class="form-group row mb-4">
                <label for="nev" class="col-sm-2 form-label lead fw-bold">Jelszó</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control bg-secondary text-white"  name="jelszo"  required>
                </div>
            </div>
            <div class="container text-center">
                <div class="">
                    <button style="margin-right: 10px;" type="submit" class="btn btn-block btn-outline-success" type="button"><span class="p-2"><i class="fas fa-sign-in-alt"></i></span>Bejelentkezés</button>
                    <a href="/registration" class="btn btn-block btn-outline-info" type="button"><span class="p-2"><i class="fa fa-user-plus"></i></span>Regisztráció</a>
                </div>
            </div>
    </form>
</div>