<h1 class="text-center my-4">Meccs Módosítás</h1>

<div class="container">
    <form method="POST" action="/meccs-szerkesztes/<?= $params["match"]["Id"] ?>">
        <div id="meccsek" class="container">
            <div class="form-group row mb-4">
                <div class="col-lg-2 "></div>
                <div class="col-lg-2 ">
                    <label for="hazai-eredmeny" class="col-form-label lead"><?= $params["match"]["hazai"] ?></label>
                </div>
                <div class="col-lg-2 ">
                    <input name="hazai-eredmeny" type="number" min="0" class="form-control" required>
                </div>
                <div class="col-lg-2 ">
                    <label for="vendeg-eredmeny" class="col-lg-1  col-form-label lead"><?= $params["match"]["vendeg"] ?></label>
                </div>
                <div class="col-lg-2 ">
                    <input name="vendeg-eredmeny" type="number" min="0" class="form-control" required>
                </div>
            </div>
        </div>
        <div class="container text-center">
            <div class="">
                <button id="uj-meccs" style="margin-right: 10px;" class="btn btn-block btn-outline-warning" type="submit"><span class="p-2"><i class="fas fa-pencil-alt"></i></span> Müdosítás</button>
                <a href="/bajnoksag/<?= $params["match"]["bajnoksagId"] ?>" class="btn btn-block btn-outline-danger" type="button"><span class="p-2"><i class="fas fa-sign-out-alt"></i></span> Vissza</a>
            </div>
        </div>
    </form>
</div>