<h1 class="text-center my-4">Regisztráció</h1>

<div class="container">
    <form method="POST" action="/registration">
        <div id="meccsek" class="container">
            <div class="form-group row mb-4">
                <label for="nev" class="col-sm-2 col-form-label">Név</label>
                <div class="col-sm-10">
                    <input type="text"  class="form-control" name="nev"  required>
                </div>
            </div>
            <div class="form-group row mb-4">
                <label for="nev" class="col-sm-2 col-form-label">Jelszó</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control"  name="jelszo"  required>
                </div>
            </div>
            <div class="container text-center">
                <div class="">
                    <button type="submit" class="btn btn-block btn-outline-info" type="button"><span class="p-2"><i class="fas fa-user"></i></span>Regisztráció</button>
                </div>
            </div>
    </form>
</div>