<h1 class="text-center my-4">Új meccsek</h1>

<div class="container">
    <form method="POST" action="/uj-meccsek/<?= $params["championshipId"] ?>">
        <div id="meccsek"  class="container">
            <div class="form-group row mb-4 text-white">
                <label for="hazai" class="col-lg-1 form-label lead mb-2 fw-bold">Hazai</label>
                <div class="col-lg-2 ">
                    <select name="hazai[]" class="form-select mb-2 bg-secondary text-white" required>
                        <option value="" selected disabled>Kérem válasszon</option>
                        <?php foreach ($params["teams"] as $team): ?>
                            <option value="<?= $team["id"] ?>"><?= $team["nev"] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <label for="vendeg" class="col-lg-1 form-label lead mb-2 fw-bold">Vendég</label>
                <div class="col-lg-2 ">
                    <select name="vendeg[]" class="form-select bg-secondary text-white" required>
                    <option value="" selected disabled>Kérem válasszon</option>
                        <?php foreach ($params["teams"] as $team): ?>
                            <option value="<?= $team["id"] ?>"><?= $team["nev"] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <label for="csoport" class="col-lg-1 form-label lead mb-2 fw-bold">Csoport</label>

                <div class="col-lg-1 ">
                    <input name="csoport[]" type="text" class="form-control bg-secondary text-white" required>
                </div>
                <label for="kezdes" class="col-lg-1  form-label lead mb-2 fw-bold">Kezdés</label>
                <div class="col-lg-2 ">
                    <input name="kezdes[]" type="datetime-local" class="form-control bg-secondary text-white" required>
                </div>
                <div class="col-lg-1 "></div>
            </div>
        </div>
        <div class="container text-center">
            <div class="">
                <button id="uj-meccs" style="margin-right: 10px;" class="btn btn-block btn-outline-success" type="button"><span class="p-2"><i class="fas fa-plus"></i></span> Új meccs</button>
                <button type="submit" class="btn btn-block btn-outline-danger" type="button"><span class="p-2"><i class="fas fa-save"></i></span> Mentés</button>
            </div>
        </div>
    </form>
</div>

<script>
    let ujMeccs = document.querySelector("#uj-meccs");
    let meccsek = document.querySelector("#meccsek");

    let ujMeccsSor = `
            <div id="" class="form-group row mb-4 text-white">
                <label for="hazai" class="col-lg-1 form-label lead mb-2 fw-bold">Hazai</label>
                <div class="col-lg-2 ">
                    <select name="hazai[]" class="form-select mb-2 bg-secondary text-white" required>
                        <option value="" selected disabled>Kérem válasszon</option>
                            <?php foreach ($params["teams"] as $team): ?>
                                <option value="<?= $team["id"] ?>"><?= $team["nev"] ?></option>
                            <?php endforeach; ?>
                    </select>
                </div>
                <label for="vendeg" class="col-lg-1 form-label lead mb-2 fw-bold">Vendég</label>
                <div class="col-lg-2 ">
                    <select name="vendeg[]" class="form-select bg-secondary text-white" required>
                    <option value="" selected disabled>Kérem válasszon</option>
                        <?php foreach ($params["teams"] as $team): ?>
                            <option value="<?= $team["id"] ?>"><?= $team["nev"] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <label for="csoport" class="col-lg-1 form-label lead mb-2 fw-bold">Csoport</label>
                <div class="col-lg-1 ">
                    <input name="csoport[]" type="text" class="form-control bg-secondary text-white" required>
                </div>
                <label for="kezdes" class="col-lg-1  form-label lead mb-2 fw-bold">Kezdés</label>
                <div class="col-lg-2 mb-2">
                    <input name="kezdes[]" type="datetime-local" class="form-control bg-secondary text-white" required>
                </div>
                <div class="col-lg-1 text-center">
                    <button onclick="deleteRow(this)" class="btn btn-block btn-outline-danger" type="button"><span class="p-2"><i class="fas fa-times"></i></span></button>
                </div>
            </div>
        `;

    ujMeccs.addEventListener("click", () => {
        meccsek.insertAdjacentHTML("beforeend", ujMeccsSor);
    })

    function deleteRow(current){
        current.closest(".form-group").remove();
    }

</script>